### ISSUE TITLE
Test fit of the sun not generating spectra or atmosphere

### ISSUE THREAD

**Issue by tzdwi** [TSFitPy-developers/TSFitPy#54]
Hi there,

I'm trying to get TSFitPy installed and working on my Mac Studio. I've followed the installation instructions, and managed to get everything compiled ok using GNU fortran v13.1.0. I tried the test case as described in the README (copying the UVES solar spectrum over to `TSFitPy/input_data/observed_spectra/`, copying the configuration file to `TSFitPy/input_data/tsfitpy_input_configuration_sun_test.cfg`, and setting `compiler=gnu` within the config file) before running `python main.py ./input_files/tsfitpy_input_configuration_sun_test.cfg`. When that happens, it looks like turbo spectrum isn't successfully generating spectra (terminal output copied below). This seems similar to #9, though with a different fortran compiler. Any help here would be greatly appreciated!

Thanks, 
Trevor

----
Terminal output (paths obfuscated):
```
./input_files/tsfitpy_input_configuration_sun_test.cfg
Start of the fitting: Jul-25-2023-11-27-23_0.47289418535843364
IMPORTANT UPDATE:
Update 24.05.2023. Currently the assumption is that the third column in the observed spectra is sigmai.e. the error in the observed spectra (sqrt(variance)). If this is not the case, please change the spectra.If none is given, the error will be assumed to be 1.0. This error is taken into account in chisqr calculation



Fitting data at /path/to/TSFitPy/./input_files/observed_spectra/ with resolution 0.0 and rotation 0.0
Temporary directory name: /path/to/TSFitPy/./temp_directory/Jul-25-2023-11-27-23_0.47289418535843364/
Fitting 1 element(s): ['Fe']


Checking inputs


Done doing some basic checks. Consider reading the messages above, if there are any. Can be useful if it crashes.


Trimming down the linelist to only lines within segments for faster fitting
Finished trimming linelist
/path/to/TSFitPy/./input_files/observed_spectra/UVES_Sun-1_cleaned_norm.txt
No error sigma given in 3rd column, setting to 1
Fitting UVES_Sun-1_cleaned_norm.txt
Teff = 5771.0; logg = 4.44; RV = 0.0
Fitting line at 5415.199 angstroms
5415.199 5414.95 5415.46 5410.95 5419.46
didn't generate spectra or atmosphere
 [Fe/H]=-0.8725455661088545 rv=9999 vmic=1.0304552293439193 vmac=9999 rotation=9999 chisqr=9999.9999
didn't generate spectra or atmosphere
 [Fe/H]=0.316995175610843 rv=9999 vmic=1.0833237681941474 vmac=9999 rotation=9999 chisqr=9999.9999
didn't generate spectra or atmosphere
 [Fe/H]=-2.062086307828552 rv=9999 vmic=1.0058868340179121 vmac=9999 rotation=9999 chisqr=9999.9999
didn't generate spectra or atmosphere
 [Fe/H]=-0.57516038067893 rv=9999 vmic=1.0410192256010806 vmac=9999 rotation=9999 chisqr=9999.9999
didn't generate spectra or atmosphere
 [Fe/H]=-0.8725455661088545 rv=9999 vmic=1.0304552293439193 vmac=9999 rotation=9999 chisqr=9999.9999
[-0.87254557]
/path/to/TSFitPy/./temp_directory/Jul-25-2023-11-27-23_0.47289418535843364/UVES_Sun-1_cleaned_norm.txt0/0.6581874613896913/spectrum_00000000.spec not found. Failed spectra generation completely, line is not fitted at all, not saving spectra then
Total runtime was 0.04 minutes.
Fitting line at 5441.339 angstroms
5441.339 5441.12 5441.58 5437.12 5445.58
didn't generate spectra or atmosphere
 [Fe/H]=-0.9820604530017091 rv=9999 vmic=1.0270105546834136 vmac=9999 rotation=9999 chisqr=9999.9999
didn't generate spectra or atmosphere
 [Fe/H]=0.3998145209304237 rv=9999 vmic=1.0880583925579892 vmac=9999 rotation=9999 chisqr=9999.9999
didn't generate spectra or atmosphere
 [Fe/H]=-2.3639354269338417 rv=9999 vmic=1.0041542856804366 vmac=9999 rotation=9999 chisqr=9999.9999
didn't generate spectra or atmosphere
 [Fe/H]=-0.6365917095186758 rv=9999 vmic=1.038692054570345 vmac=9999 rotation=9999 chisqr=9999.9999
didn't generate spectra or atmosphere
 [Fe/H]=-0.9820604530017091 rv=9999 vmic=1.0270105546834136 vmac=9999 rotation=9999 chisqr=9999.9999
[-0.98206045]
/path/to/TSFitPy/./temp_directory/Jul-25-2023-11-27-23_0.47289418535843364/UVES_Sun-1_cleaned_norm.txt0/0.6564023709760531/spectrum_00000000.spec not found. Failed spectra generation completely, line is not fitted at all, not saving spectra then
Total runtime was 0.03 minutes.
TSFitPy had normal termination
Fitting completed
End of the fitting: Jul-25-2023-11-27-28
```

**Comment by stormnick** [comment]
Hi, 

Could you please run with `debug=2` in the config file? That will allow to see the Fortran output.

Also, I cannot 100% confirm whether it works with the GNU fortran, because official TurboSpectrum documentation mentions that it is not supported atm. At the very least, I know that Intel fortran (ifort) would work faster. So I would recommend to check whether you can install it [from here](https://www.intel.com/content/www/us/en/developer/tools/oneapi/fortran-compiler.html) regardless (assuming Intel chip on your Mac).

**Comment by tzdwi** [comment]
Thanks for the quick response! Text file with terminal output is [here](https://github.com/TSFitPy-developers/TSFitPy/files/12186149/term_output.txt). 

Unfortunately my desktop is on Apple silicon (M1 Ultra, if that helps). My laptop has an Intel chip but the end goal is a fit of ~50 spectra, so the desktop would be preferable.

**Comment by JGerbs13** [comment]
It looks like there is a fortran library missing based on this line in the Turbospectrum bsyn output, which is causing Turbospectrum to fail.

"dyld[3550]: dyld cache '(null)' not loaded: syscall to map cache into shared region failed
dyld[3550]: Library not loaded: /usr/lib/libSystem.B.dylib"

You could look into getting that library assuming it exists for the GNU compiler. If that gets too complicated, it might be easiest just to run it on your laptop. How many lines are you looking to fit per spectrum?

**Comment by tzdwi** [comment]
A quick google reveals lots of folks missing that library, but not a lot of solutions. Apparently a similarly named library exists on my machine in `/Applications/Xcode.app/Contents/`[many layers of directories]`/usr/lib/libSystem.B.dylib`. I suppose I could put a symlink to it in `/usr/lib`, but I'm pretty out of my depth here so I don't know if this is remotely a good idea or not.  Otherwise, installing on my laptop indeed seems the way to go.

In terms of number of lines, this is my first time doing this kind of work, so unsure; hoping to get at least Fe, C, N, and O for ~40 FGK stars.

**Comment by stormnick** [comment]
I have tried searching for your issue myself and it seems more like the issue with the Mac itself (perhaps one of the latest updates based on some people?). I have an M2 chip myself, although I did hear that some people were able to instal an older ifort compiler for an M1 Mac chip and that it works quite fine somehow. 

Alternatively, laptop can work. The code has been highly optimised, so it takes only around 1-2 minutes on a laptop CPU to fit 1 line. 40 stars for 4 elements are totally doable, I think you will only "struggle" with Fe determination depending on how many lines you choose.

Also this code is parallelised on several cores (fitting of stars or even individual lines can be fitted in parallel if you turn that on in the config file). So if your laptop has say 4 CPU cores, then you can run the code 4 times faster in parallel.

**Comment by tzdwi** [comment]
Gotcha. Since this is on my end, I'll close this issue. Thanks both for the help!
