### ISSUE TITLE
Turbospectrum Spherical Model Can't Run on Mac M4

### ISSUE THREAD

**Issue by danangsetyo5364** [TSFitPy-developers/TSFitPy#77]
Hello, I just got my new MacBook and I want to run TS here. I have some experience to install and run this program on Windows/WSL before and it run smoothly. However, when I try to calculate abundance for an element (again I have checked that all the parameters are same, also the needed files), and TS could not synthesize the spectra, and chi_sq show : chi_sq=99999.

However when I test to run with template given by TSFit.py, it run as usual. anybody have same problem here?

*I think after some research, my problem is caused by spherical model that I need for my star (giant stars), anybody know how to solve this?

Cheers,
Danang

**Comment by stormnick** [comment]
Same issue as here?
https://github.com/bertrandplez/Turbospectrum_NLTE/issues/17 I don't think
anyone has any working solution, except for using a non-gfortran compiler
afaik
