### ISSUE TITLE
Possibility to use another atmospheric model?

### ISSUE THREAD

**Issue by danangsetyo5364** [TSFitPy-developers/TSFitPy#78]
Hai I want to ask if possible to use another atmospheric model other than MARCS using TSFit.py?

Cheers,
Danang

**Comment by danangsetyo5364** [comment]
ah okey how about the ATLAS9?

**Comment by stormnick** [comment]
Not natively, no. Theoretically, you could always change how models are interpolated, as long as TS supports it. But NLTE departure grids are only calculated for standard MARCS models and STAGGER <3D>.

**Comment by danangsetyo5364** [comment]
So basically if we used another atmospheric model, TS will run as usual but
we could not use NLTE calculation?

**Comment by stormnick** [comment]
To be more accurate, TS will only run LTE in that case. NLTE requires precomputed grid of departure coefficients, which was only done for standard MARCS atmospheres and <3D> STAGGER grid.
